// GENERATED by scripts/gen-tool-catalog.mjs from forgeax-extension.json. Do not edit.

/** Service package the extension launches, pinned to the version it was built against. */
export const SERVICE_PACKAGE = "@forgeax-extension/narrative";
export const SERVICE_VERSION = "0.2.0";

export interface CatalogEntry {
  readonly name: string;
  readonly id: string;
  readonly description: string;
  readonly params: readonly string[];
  readonly hints: Readonly<Record<string, string>>;
  readonly required: readonly string[];
  readonly requireConfirm: boolean;
}

export const CATALOG: readonly CatalogEntry[] = [
  {
    "name": "analyze-impact",
    "id": "narrative:analyze-impact",
    "description": "重生成前预判:对若干节点的拟改动做差异+影响分析,返回受影响范围",
    "params": [
      "sourceDir",
      "modifications"
    ],
    "hints": {
      "sourceDir": "运行输出目录名",
      "modifications": "拟改动列表"
    },
    "required": [
      "sourceDir",
      "modifications"
    ],
    "requireConfirm": false
  },
  {
    "name": "cancel-run",
    "id": "narrative:cancel-run",
    "description": "取消/暂停正在运行的管线 · 已跑完的步保留断点，随后可用 resume-pipeline 续跑",
    "params": [
      "runId"
    ],
    "hints": {
      "runId": "Run ID of the currently running pipeline to cancel"
    },
    "required": [
      "runId"
    ],
    "requireConfirm": false
  },
  {
    "name": "confirm-asset",
    "id": "narrative:confirm-asset",
    "description": "确认或撤销确认一份产物 · 可钉住版本号（缺省跟随最新）",
    "params": [
      "entryKey",
      "path",
      "pipelineId",
      "version",
      "confirmed"
    ],
    "hints": {
      "entryKey": "条目键（任务的磁盘目录名）",
      "path": "要确认的产物，`<group>/<相对路径>`，取自 narrative:list-files",
      "pipelineId": "泳道；缺省 = 主管线。次管线产物必须带上，否则会与主管线同名产物互相顶掉",
      "version": "钉住这一稿；缺省表示跟随最新",
      "confirmed": "false 表示撤销确认；缺省视为确认"
    },
    "required": [
      "entryKey",
      "path"
    ],
    "requireConfirm": false
  },
  {
    "name": "create-entry",
    "id": "narrative:create-entry",
    "description": "建/改条目 · 与节点入口同一份 _entry.json · 先建条目再带 entryKey 开跑",
    "params": [
      "key",
      "inputType",
      "userInput",
      "tags",
      "routeGroup",
      "tier",
      "mode",
      "genreCode",
      "storyType",
      "storyTheme",
      "complexity",
      "locale"
    ],
    "hints": {
      "key": "Entry key, used verbatim as the output directory name. Must be a safe relative directory name (no slashes, no '..').",
      "inputType": "How the requirement was given: free text, tag selection, or uploaded works. Recorded so the task panel can show what the author actually submitted.",
      "userInput": "The requirement text for this entry.",
      "tags": "Raw tag selections when inputType is 'tags': { selections, customTexts }. Not used for routing, recorded for restore.",
      "storyType": "Narrative type axis code (see narrative:list-axes).",
      "storyTheme": "Narrative theme axis code (see narrative:list-axes)."
    },
    "required": [
      "key"
    ],
    "requireConfirm": false
  },
  {
    "name": "export-result",
    "id": "narrative:export-result",
    "description": "导出叙事结果到项目目录",
    "params": [
      "runId",
      "slug",
      "targetDir"
    ],
    "hints": {
      "runId": "Run ID of a completed pipeline run",
      "slug": "Game slug for the output path. Defaults to '_default'.",
      "targetDir": "Explicit export directory. Overrides slug-based default path (.forgeax/games/<slug>/narrative/)."
    },
    "required": [
      "runId"
    ],
    "requireConfirm": false
  },
  {
    "name": "get-ip-dna",
    "id": "narrative:get-ip-dna",
    "description": "只读:按 runId 读取 IP DNA 层级树摘要(节点/层级/标题),用于审阅与可视化",
    "params": [
      "runId"
    ],
    "hints": {
      "runId": "IP DNA 运行 id(story_timestamp 或目录名)"
    },
    "required": [
      "runId"
    ],
    "requireConfirm": false
  },
  {
    "name": "get-pipeline-nodes",
    "id": "narrative:get-pipeline-nodes",
    "description": "读取正在运行的管线各步骤节点及状态(仅对内存中活动 run 有效)",
    "params": [
      "runId"
    ],
    "hints": {
      "runId": "活动运行 id"
    },
    "required": [
      "runId"
    ],
    "requireConfirm": false
  },
  {
    "name": "get-review",
    "id": "narrative:get-review",
    "description": "读取某次运行的评审状态(各步骤 approved/rejected/反馈)",
    "params": [
      "dir"
    ],
    "hints": {
      "dir": "运行输出目录名"
    },
    "required": [
      "dir"
    ],
    "requireConfirm": false
  },
  {
    "name": "get-run-status",
    "id": "narrative:get-run-status",
    "description": "查询管线运行状态 · 步骤进度 · 结果获取",
    "params": [
      "runId",
      "includeResult"
    ],
    "hints": {
      "runId": "Run ID returned by start-pipeline",
      "includeResult": "When true and run is completed, fetch and include the full NarrativeContext result"
    },
    "required": [
      "runId"
    ],
    "requireConfirm": false
  },
  {
    "name": "get-stale-steps",
    "id": "narrative:get-stale-steps",
    "description": "给定起始步骤,返回会因其变更而过期、需重生成的下游步骤与字段",
    "params": [
      "sourceDir",
      "fromStepId"
    ],
    "hints": {
      "sourceDir": "运行输出目录名",
      "fromStepId": "起始步骤 id"
    },
    "required": [
      "sourceDir",
      "fromStepId"
    ],
    "requireConfirm": false
  },
  {
    "name": "get-story-tree",
    "id": "narrative:get-story-tree",
    "description": "读取某次运行的叙事树结构(分层节点),用于把握整体故事骨架",
    "params": [
      "dir"
    ],
    "hints": {
      "dir": "运行输出目录名(checkpoint 所在)"
    },
    "required": [
      "dir"
    ],
    "requireConfirm": false
  },
  {
    "name": "get-team",
    "id": "narrative:get-team",
    "description": "查看某个专属团队 · 蒸馏状态与风格签名 / 禁区 / 各席位技能",
    "params": [
      "teamId"
    ],
    "hints": {
      "teamId": "Team id from narrative:list-teams."
    },
    "required": [
      "teamId"
    ],
    "requireConfirm": false
  },
  {
    "name": "ip-dna-analyze-impact",
    "id": "narrative:ip-dna-analyze-impact",
    "description": "IP DNA 改写影响面分析(蓝图§10/§15):给定改动字段,沿 data-atlas 推导受影响下游与输入层级节点",
    "params": [
      "runId",
      "changedKeys"
    ],
    "hints": {
      "runId": "IP DNA 运行 id",
      "changedKeys": "拟改动的 data-atlas 字段键列表(如 ['A.characters'])"
    },
    "required": [
      "runId",
      "changedKeys"
    ],
    "requireConfirm": false
  },
  {
    "name": "ip-dna-cancel",
    "id": "narrative:ip-dna-cancel",
    "description": "取消生产(§5.1):取消正在运行的 IP DNA 异步任务(与前端「取消生成」按钮能力对等)",
    "params": [
      "jobId"
    ],
    "hints": {
      "jobId": "任务 id(由 async 阶段门返回)"
    },
    "required": [
      "jobId"
    ],
    "requireConfirm": false
  },
  {
    "name": "ip-dna-confirm-scope",
    "id": "narrative:ip-dna-confirm-scope",
    "description": "确认裁剪范围(§4.4 第①步):回填嵌套层级选择;缺省=全量。确认门终点",
    "params": [
      "runId",
      "scopeSelections",
      "scopeFull",
      "adaptationNotes"
    ],
    "hints": {
      "runId": "运行 id(=时间戳_故事名)",
      "scopeSelections": "裁剪范围。两种形态二选一:(a) 嵌套层级选择 nodeId(+childRange);(b) 最小单元闭区间 leafRange(每部=一个区间,起止为叶子 id,文档序)。缺省=全量改编",
      "scopeFull": "是否全量(无 selections 时默认 true)",
      "adaptationNotes": "作者自定义改编补充(§5.1 自由文本):描述所选范围想怎么改;下游据此判断改哪些维度并定点替换。缺省=忠实把原 IP 转化为目标品类叙事"
    },
    "required": [
      "runId"
    ],
    "requireConfirm": false
  },
  {
    "name": "ip-dna-confirm-units",
    "id": "narrative:ip-dna-confirm-units",
    "description": "确认游戏单元 + 改编维度(§4.4 第②③步):回填 game_unit_plan/adaptation_dimensions/mode",
    "params": [
      "runId",
      "gameUnitPlan",
      "adaptationDimensions",
      "mode",
      "targetUnits"
    ],
    "hints": {
      "runId": "运行 id(=时间戳_故事名)",
      "gameUnitPlan": "用户精确选填的游戏单元规划(§4.4 第②步);提供则优先采用并直接生成 N 个游戏单元,覆盖默认切分。契约:一行/一部=一个游戏单元(1:1),units 数即游戏单元数。",
      "adaptationDimensions": "改编维度(叙事层级数+模板字段);缺省=全维度模板",
      "mode": "完整游戏模式(仅在不传 gameUnitPlan 时按默认切分参考)",
      "targetUnits": "默认切分时'每游戏单元最小单元数'(默认 25,非游戏单元个数);传 gameUnitPlan 时忽略"
    },
    "required": [
      "runId"
    ],
    "requireConfirm": false
  },
  {
    "name": "ip-dna-decompose",
    "id": "narrative:ip-dna-decompose",
    "description": "IP 半自动(§5 步骤6-10):体量超线时按标记/单元闭环拆解→再标准化→重写骨架层级树",
    "params": [
      "runId"
    ],
    "hints": {
      "runId": "运行 id(=时间戳_故事名)"
    },
    "required": [
      "runId"
    ],
    "requireConfirm": false
  },
  {
    "name": "ip-dna-extract",
    "id": "narrative:ip-dna-extract",
    "description": "生成 scoped IP DNA(§5 步骤4):仅提取不跑下游生成,消费已确认裁剪范围/单元/维度",
    "params": [
      "runId",
      "pipelineFamily",
      "tier",
      "generationMode",
      "complexity",
      "maxGameUnits",
      "equipOperators",
      "model",
      "async"
    ],
    "hints": {
      "runId": "运行 id(=时间戳_故事名)",
      "pipelineFamily": "可选,生成管线族",
      "tier": "可选,透传生成管线 tier",
      "generationMode": "可选,透传生成管线 mode",
      "complexity": "可选,目标复杂度 1-5",
      "maxGameUnits": "可选,最多处理多少个游戏单元",
      "equipOperators": "为每个游戏单元装备三视角算子并消费,默认 false",
      "model": "可选,覆盖默认 LLM 模型",
      "async": "true 立即返回 jobId,轮询 ip-dna-get-job"
    },
    "required": [
      "runId"
    ],
    "requireConfirm": false
  },
  {
    "name": "ip-dna-generate",
    "id": "narrative:ip-dna-generate",
    "description": "开始生成(§5 步骤4→5):提取(=生成 scoped IP DNA)+下游叙事生成自动串跑。改编范围确认后触发,中途不暂停",
    "params": [
      "runId",
      "pipelineFamily",
      "tier",
      "generationMode",
      "complexity",
      "maxGameUnits",
      "equipOperators",
      "model",
      "async"
    ],
    "hints": {
      "runId": "运行 id(=时间戳_故事名)",
      "pipelineFamily": "可选,生成管线族",
      "tier": "可选,透传生成管线 tier",
      "generationMode": "可选,透传生成管线 mode",
      "complexity": "可选,目标复杂度 1-5",
      "maxGameUnits": "可选,最多生成多少个游戏单元",
      "equipOperators": "为每个游戏单元装备三视角算子并消费,默认 false",
      "model": "可选,覆盖默认 LLM 模型",
      "async": "true 立即返回 jobId,轮询 ip-dna-get-job"
    },
    "required": [
      "runId"
    ],
    "requireConfirm": false
  },
  {
    "name": "ip-dna-get-hierarchy",
    "id": "narrative:ip-dna-get-hierarchy",
    "description": "只读:摄入后的层级树 + 默认裁剪/单元/维度 + 体量,供确认裁剪范围引导(半自动/agent 共用)",
    "params": [
      "runId"
    ],
    "hints": {
      "runId": "运行 id(=时间戳_故事名)"
    },
    "required": [
      "runId"
    ],
    "requireConfirm": false
  },
  {
    "name": "ip-dna-get-job",
    "id": "narrative:ip-dna-get-job",
    "description": "轮询异步任务(ingest/extract/generate)的状态/进度/结果",
    "params": [
      "jobId"
    ],
    "hints": {
      "jobId": "任务 id(由 async 阶段门返回)"
    },
    "required": [
      "jobId"
    ],
    "requireConfirm": false
  },
  {
    "name": "ip-dna-ingest",
    "id": "narrative:ip-dna-ingest",
    "description": "IP 半自动阶段门①(§5.1):摄入+标准化+建树(含干扰项过滤),停在确认裁剪范围前。返回层级树骨架+体量/拆解建议+默认裁剪/单元/维度",
    "params": [
      "files",
      "title",
      "decompose",
      "model",
      "async",
      "storyTimestamp"
    ],
    "hints": {
      "files": "输入文件(至少一个)。三种给法任选:path 工程内路径(聊天附件走这条)、content 文本、contentBase64 二进制",
      "title": "可选,故事标题(缺省取首文件名)",
      "decompose": "超体量时执行拆解闭环(再标准化),默认 false",
      "model": "可选,覆盖默认 LLM 模型",
      "async": "true 立即返回 jobId,轮询 ip-dna-get-job 取层级树摘要",
      "storyTimestamp": "可选,指定完整故事时间戳(续跑/对齐 jobId)"
    },
    "required": [
      "files"
    ],
    "requireConfirm": false
  },
  {
    "name": "ip-dna-start",
    "id": "narrative:ip-dna-start",
    "description": "IP DNA 端到端入口(蓝图§5):上传/指定全模态 IP 文件 → 理解 → 改编 → (可选)全品类游戏叙事生成。可能较久,默认仅产出 IP DNA+改编指令+生成输入",
    "params": [
      "files",
      "title",
      "mode",
      "scopeSelections",
      "gameUnitPlan",
      "adaptationDimensions",
      "adaptationNotes",
      "targetUnits",
      "complexity",
      "runGeneration",
      "maxGameUnits",
      "pipelineFamily",
      "tier",
      "generationMode",
      "routeGroup",
      "genreCode",
      "model"
    ],
    "hints": {
      "files": "输入文件(至少一个)。三种给法任选:path 工程内路径(聊天附件走这条)、content 文本、contentBase64 二进制",
      "title": "可选,故事标题(缺省取首文件名)",
      "mode": "完整游戏模式,默认 series",
      "scopeSelections": "§4.4 第①步对话产物:裁剪范围(嵌套层级选择)。缺省=全量改编",
      "gameUnitPlan": "§4.4 第②步对话产物:用户精确选填的游戏单元规划。缺省=默认切分",
      "adaptationDimensions": "§4.4 第③步对话产物:改编维度(叙事层级数 + 模板字段)。缺省=全维度模板",
      "adaptationNotes": "§5.1 自定义补充:作者改编意图自由文本(描述所选范围想怎么改);下游据此判断改哪些维度并定点替换。缺省=忠实把原 IP 转化为目标品类叙事",
      "targetUnits": "可选,默认切分时'每游戏单元最小单元数'(默认 25,非游戏单元个数);传 gameUnitPlan 时忽略",
      "complexity": "可选,目标复杂度 1-5",
      "runGeneration": "是否真正跑生成管线,默认 false(仅理解+改编)",
      "maxGameUnits": "可选,最多生成多少个游戏单元",
      "pipelineFamily": "可选,生成管线族",
      "tier": "可选,透传生成管线 tier",
      "generationMode": "可选,透传生成管线 mode",
      "routeGroup": "可选,ROUTING 路由组(§5.1),与主管线对齐",
      "genreCode": "可选,品类编码(如 rpg-jrpg/adv-interactive);决定下游 vn/rpg 生成管线",
      "model": "可选,覆盖默认 LLM 模型"
    },
    "required": [
      "files"
    ],
    "requireConfirm": false
  },
  {
    "name": "list-assets",
    "id": "narrative:list-assets",
    "description": "列出某条目里作者已确认为定稿的产物 · 下游生成只引用这张表里的文件",
    "params": [
      "entryKey",
      "pipelineId"
    ],
    "hints": {
      "entryKey": "条目键（任务的磁盘目录名）；不是 runId —— runId 是内存态，重启即失效",
      "pipelineId": "只看某条泳道；缺省给整个条目的定稿清单"
    },
    "required": [
      "entryKey"
    ],
    "requireConfirm": false
  },
  {
    "name": "list-axes",
    "id": "narrative:list-axes",
    "description": "三轴词表 · 叙事类型 / 题材 / 结构 · 填 storyType 与 storyTheme 前先查",
    "params": [],
    "hints": {},
    "required": [],
    "requireConfirm": false
  },
  {
    "name": "list-files",
    "id": "narrative:list-files",
    "description": "列出某次运行(runId 或输出目录名)的全部产出文件",
    "params": [
      "runId"
    ],
    "hints": {
      "runId": "运行 id 或输出目录名"
    },
    "required": [
      "runId"
    ],
    "requireConfirm": false
  },
  {
    "name": "list-genres",
    "id": "narrative:list-genres",
    "description": "列出全部游戏品类(按大类分组,含 code/名称/tier/叙事比重/模板),选 genreCode 前先查",
    "params": [],
    "hints": {},
    "required": [],
    "requireConfirm": false
  },
  {
    "name": "list-modes",
    "id": "narrative:list-modes",
    "description": "列出各 tier 可用的运行模式/模板及步骤数",
    "params": [],
    "hints": {},
    "required": [],
    "requireConfirm": false
  },
  {
    "name": "list-runs",
    "id": "narrative:list-runs",
    "description": "列出历史运行记录 · 支持断点续跑与分叉重生成",
    "params": [
      "limit"
    ],
    "hints": {
      "limit": "Max number of history entries to return"
    },
    "required": [],
    "requireConfirm": false
  },
  {
    "name": "list-seats",
    "id": "narrative:list-seats",
    "description": "列出全部二十席叙事单品助手 · id/名称/kind/是否能被单独调用(canRunStandalone)/单跑前还缺什么输入",
    "params": [],
    "hints": {},
    "required": [],
    "requireConfirm": false
  },
  {
    "name": "list-teams",
    "id": "narrative:list-teams",
    "description": "列出自定义专属创作团队 · 单本模板助手与作家创作顾问 · 只有 ready 的能带进生成",
    "params": [],
    "hints": {},
    "required": [],
    "requireConfirm": false
  },
  {
    "name": "load-history",
    "id": "narrative:load-history",
    "description": "加载某条历史运行记录的详情(拿到 tier/mode/result 及目录名,供后续续跑/编辑)",
    "params": [
      "key"
    ],
    "hints": {
      "key": "历史记录 key(来自 list-runs)"
    },
    "required": [
      "key"
    ],
    "requireConfirm": false
  },
  {
    "name": "read-file",
    "id": "narrative:read-file",
    "description": "读取某次运行下指定相对路径的产出文件内容(json/文本,自动截断防爆上下文)",
    "params": [
      "runId",
      "filePath"
    ],
    "hints": {
      "runId": "运行 id 或输出目录名",
      "filePath": "相对该运行目录的文件路径,如 narrative.md / characters/hero.md"
    },
    "required": [
      "runId",
      "filePath"
    ],
    "requireConfirm": false
  },
  {
    "name": "regenerate-step",
    "id": "narrative:regenerate-step",
    "description": "重生成指定步骤 · 支持用户指令注入与节点级过滤",
    "params": [
      "sourceDir",
      "fromStepId",
      "userInstructions",
      "stopAfterStep",
      "model",
      "skipSteps",
      "nodeFilter",
      "editDrafts"
    ],
    "hints": {
      "sourceDir": "Source run directory key (from list-runs 'key' field)",
      "fromStepId": "Step ID to regenerate from (e.g. 'story_framework', 'outline_batch')",
      "userInstructions": "Natural language instructions for how to change the regenerated content",
      "stopAfterStep": "Stop pipeline after this step instead of running to completion",
      "model": "Override LLM model for this regeneration",
      "skipSteps": "Step IDs to skip during regeneration",
      "nodeFilter": "Per-step node ID filter: only regenerate listed nodes within each step (partial regen)",
      "editDrafts": "Pre-edited content drafts keyed by stepId or 'stepId::nodeId'"
    },
    "required": [
      "sourceDir",
      "fromStepId"
    ],
    "requireConfirm": false
  },
  {
    "name": "restore-original",
    "id": "narrative:restore-original",
    "description": "把某一步(或某个节点)的内容还原为模型原稿，撤掉编辑账本里那一条 · 没存过原稿则报错",
    "params": [
      "sourceDir",
      "stepId",
      "nodeId"
    ],
    "hints": {},
    "required": [
      "sourceDir",
      "stepId"
    ],
    "requireConfirm": false
  },
  {
    "name": "resume-pipeline",
    "id": "narrative:resume-pipeline",
    "description": "从 checkpoint 断点续跑某次未完成的运行(写入同一目录)",
    "params": [
      "dir",
      "model"
    ],
    "hints": {
      "dir": "运行输出目录名(含 checkpoint)",
      "model": "可选,覆盖默认 LLM 模型"
    },
    "required": [
      "dir"
    ],
    "requireConfirm": false
  },
  {
    "name": "run-seat",
    "id": "narrative:run-seat",
    "description": "按席位 id 单独跑一个叙事单品助手(二十席之一) · 不遍历全管线 · 给 entryKey 可并入该条目落盘供后续管线消费",
    "params": [
      "seatId",
      "userInput",
      "ctx",
      "inputs",
      "model",
      "entryKey"
    ],
    "hints": {
      "seatId": "席位 id(先用 narrative:list-seats 查有哪些席、canRunStandalone 是否为真)，也接受直接传 step id",
      "ctx": "补齐/覆盖上下文字段，如上游席位的产出",
      "inputs": "覆盖/追加输入字段，写入后再校验 requiredInputs",
      "entryKey": "绑定到某条目并落盘(G2)；不给则只在响应体里回结果，不落盘"
    },
    "required": [
      "seatId"
    ],
    "requireConfirm": false
  },
  {
    "name": "save-step-edit",
    "id": "narrative:save-step-edit",
    "description": "改稿落盘 · 与界面文本视图保存同一端点 · 原稿自动存 _original/ 供还原 · 省略 editedContent 只回读不写盘",
    "params": [
      "sourceDir",
      "stepId",
      "nodeId",
      "editedContent",
      "userInput"
    ],
    "hints": {
      "editedContent": "省略则只回读当前内容、不写盘",
      "userInput": "这一改的说明/意图，供后续影响面分析与重新生成参考"
    },
    "required": [
      "sourceDir",
      "stepId"
    ],
    "requireConfirm": false
  },
  {
    "name": "set-review",
    "id": "narrative:set-review",
    "description": "标记某步骤的评审结论(approved/rejected/pending)并附反馈",
    "params": [
      "dir",
      "stepId",
      "status",
      "feedback",
      "regenerateRunId"
    ],
    "hints": {
      "dir": "运行输出目录名",
      "stepId": "步骤 id",
      "status": "评审结论",
      "feedback": "可选,评审反馈",
      "regenerateRunId": "可选,关联的重生成 run id"
    },
    "required": [
      "dir",
      "stepId",
      "status"
    ],
    "requireConfirm": false
  },
  {
    "name": "start-pipeline",
    "id": "narrative:start-pipeline",
    "description": "启动叙事管线 · 支持 117 品类 × 9 模板 · 自动 Tier/Mode 路由",
    "params": [
      "userInput",
      "tier",
      "mode",
      "genreCode",
      "complexity",
      "routeGroup",
      "routingMode",
      "model",
      "teamId",
      "storyType",
      "storyTheme",
      "entryKey",
      "activateSeats"
    ],
    "hints": {
      "userInput": "Story requirements in any language (free text). May include genre hints, theme, setting, character concepts, or an entire brief.",
      "tier": "Narrative intensity tier. Omit to let the pipeline auto-detect via LLM.",
      "mode": "Pipeline mode (step sequence). Omit to use tier default (design_auto).",
      "genreCode": "Explicit genre code from the 94-entry taxonomy (e.g. 'rpg-jrpg'). Skips LLM genre detection when provided.",
      "complexity": "Narrative complexity level (1=minimal, 5=maximum depth).",
      "routeGroup": "Route group: 'planning' for game design pipeline, 'narrative' for story-only.",
      "routingMode": "Routing strategy. 'auto' = full LLM detection, 'semi' = tier given / mode auto, 'manual' = both given.",
      "model": "Override LLM model for this run (e.g. 'gemini-2.5-pro'). Uses NARRATIVE_MODEL env default when omitted.",
      "teamId": "Custom creative team to bring along, distilled from user-supplied books or an author's body of work. Call narrative:list-teams first and pass an id whose status is 'ready'; other statuses are treated as no team at all. When the user mentions a team via '@', the inserted text carries 'team=<id>'.",
      "storyType": "Narrative type axis code (call narrative:list-axes for the vocabulary). Omit to let the pipeline infer it from the request text.",
      "storyTheme": "Narrative theme axis code (call narrative:list-axes for the vocabulary). Omit to let the pipeline infer it. The third axis, narrative structure, is derived server-side from type + theme and cannot be set directly.",
      "entryKey": "Entry this run belongs to, as returned by narrative:create-entry. Omit and the run mints its own timestamp directory with no _entry.json, which leaves it in the left rail with no recorded parameters. Create the entry first when you want the same entry record the node canvas produces.",
      "activateSeats": "Off-by-default polish seats to attach after plot generation. Each one rewrites the generated script in place as a new version of the same field. All off by default: three extra LLM passes over the plot layer."
    },
    "required": [
      "userInput"
    ],
    "requireConfirm": false
  }
] as const;

export const BY_NAME = new Map(CATALOG.map((entry) => [entry.name, entry]));
